SET SQL_SAFE_UPDATES = 0;


DELETE FROM UNIDADESPORCURSO;
DELETE FROM CURSOS;
DELETE FROM ESTADODECURSOSPORALUMNO;
DELETE FROM inscripcionesporalumno;

DELETE FROM USUARIOS;
DELETE FROM LOCALIDADES;
DELETE FROM PROVINCIAS;
DELETE FROM PAISES;

ALTER TABLE PAISES auto_increment=1;
ALTER TABLE PROVINCIAS auto_increment=1;
ALTER TABLE LOCALIDADES auto_increment=1;
ALTER TABLE USUARIOS auto_increment=1;
ALTER TABLE CURSOS auto_increment=1;